# values.yaml
replicaCount: 1
image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: 1.21.6
mySecretPassword: ENC[AES256_GCM,data:+JvLri9zN9f1FQf4AUpK9g==,iv:EpyQuy4kxjhm/hjX1KTr3AYkY6cxE3tNWtqHIUvYU6E=,tag:fJFMwX3n4wpKuU0RxTryYw==,type:str]
sops:
    lastmodified: "2025-10-15T03:23:45Z"
    mac: ENC[AES256_GCM,data:J+mzvCiIcAhUWGpizQHXgwKh7isI/axg/fdmIXmTw/IjGp16zwZcChXz/uRtxa4iZGJ6fAkuH51jGiRiCDN6NaiKfREpF75hqCmmC09kNJO3B7xbVbaWm1ggIlQeH5fXdJivgaEntH1rdNmFBWxYeGmXbT1mNY82dltRPD5Iob8=,iv:HaeUVXvYH2f+TtB5Cu/klPVZER2MzQuOVY8n12qsg/g=,tag:9bGRdE7i7iUVRNdG/WRocw==,type:str]
    pgp:
        - created_at: "2025-10-15T03:23:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DHICC/VIf2eASAQdAa2Yhb5qTmzrX9pHNU0IgmnDovWfJl/CoM1Lk6vBk9mMw
            9++W0NOXoWlEPE+ooaWtDw2tFzt+Q6TQz94ntMfcH5bFquzA5nmbtJKbw7Qzq86i
            1GgBCQIQ3+zg0+uDgPTyG3Si+DJW3jYbos3p4zv+P7Hlach45We6p63LT79xE1Eh
            sTdqri2J9c9tLgDqM2z8pX8GZhKoTbTsydgDDnF50UKkn0AtyUbd7MGh5UxiTMrR
            ZzG97+9BAQTJtQ==
            =VrLq
            -----END PGP MESSAGE-----
          fp: 7E379DCF9EB4EF47B7396B37F75F5CA1FB03EDE9
    encrypted_regex: ^(mySecretPassword)$
    version: 3.11.0
